version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo

    steps:
      - checkout

      # TODO Add linting

      - run:
          name: run tests
          command: python setup.py test
