version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: pycodestyle
          command: |
            pip install pycodestyle
            pycodestyle sphinx_websequencediagrams.py

      - run:
          name: pydocstyle
          command: |
            pip install pydocstyle
            pydocstyle sphinx_websequencediagrams.py

      - run:
          name: python setup.py test
          command: python setup.py test

